#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/network/if-up.d/avahi-daemon 0.8-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/resolvconf/update-libc.d/avahi-daemon 0.8-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/avahi-daemon 0.8-8\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/dbus-1/system.d/avahi-dbus.conf 0.8-9\~ -- "$@"
# End automatically added section
