#! /bin/sh

set -e

# Automatically added by dh_installdebconf/13.11.4
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


case "$1" in
    purge)
	rm -f /var/lib/cups/ppds.dat /etc/cups/raw.convs /etc/cups/raw.types
	;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac
