#!/bin/sh
set -e

# Tag to allow some debhelper commands to inject relevant code
# Automatically added by dh_icons/13.11.4
if command -v update-icon-caches >/dev/null; then
	update-icon-caches /usr/share/icons/desktop-base
fi
# End automatically added section


if [ "$1" = "remove" ] || [ "$1" = "deconfigure" ]; then
    if which update-grub2 > /dev/null ; then
        update-grub2 || true
    fi
fi

