#!/bin/sh
set -e

# Automatically added by dh_python3
if command -v py3compile >/dev/null 2>&1; then
	py3compile -p inkscape:amd64 /usr/share/inkscape
fi
if command -v pypy3compile >/dev/null 2>&1; then
	pypy3compile -p inkscape:amd64 /usr/share/inkscape || true
fi

# End automatically added section
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/bash_completion.d/inkscape 0.91-6\~ -- "$@"
# End automatically added section
