#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.10
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	deb-systemd-invoke stop 'laptop-mode.timer' 'lmt-poll.service' >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.10
if [ -z "${DPKG_ROOT:-}" ] && [ "$1" = remove ] && [ -x "/etc/init.d/laptop-mode" ] ; then
	invoke-rc.d laptop-mode stop || exit 1
fi
# End automatically added section
