#!/bin/sh
set -e

if [ "$1" = "purge" ] ; then
    delgroup --quiet --system pipewire > /dev/null || true
fi

# Automatically added by dh_installsystemduser/13.11.4
if [ "$1" = "purge" ]; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'pipewire.service' 'pipewire.socket' >/dev/null || true
	fi
fi
# End automatically added section

