#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/xdg/autostart/tracker-extract.desktop 3.1.2-1\~ -- "$@"
# End automatically added section
# Automatically added by dh_installsystemduser/13.11.4
if [ "$1" = "purge" ]; then
	if [ -z "${DPKG_ROOT:-}" ] && [ -x "/usr/bin/deb-systemd-helper" ] ; then
		deb-systemd-helper --user purge 'tracker-extract-3.service' >/dev/null || true
	fi
fi
# End automatically added section
